clone_depth: 1 # NB: this stops FIO-VERSION-GEN making tag based versions

image:
  - Visual Studio 2019

environment:
  CYG_MIRROR: http://cygwin.mirror.constant.com
  CYG_ROOT: C:\cygwin64
  MAKEFLAGS: -j 2
  matrix:
    - platform: x64
      PACKAGE_ARCH: x86_64
      CONFIGURE_OPTIONS:

install:
  - '%CYG_ROOT%\setup-x86_64.exe --quiet-mode --no-shortcuts --only-site --site "%CYG_MIRROR%" --packages "mingw64-%PACKAGE_ARCH%-zlib,mingw64-%PACKAGE_ARCH%-CUnit" > NUL'
  - SET PATH=C:\Python38-x64;%CYG_ROOT%\bin;%PATH% # NB: Changed env variables persist to later sections
  - SET PYTHONUNBUFFERED=TRUE
  - python.exe -m pip install scipy six

build_script:
  - 'bash.exe -lc "cd \"${APPVEYOR_BUILD_FOLDER}\" && ./configure --disable-native --extra-cflags=\"-Werror\" ${CONFIGURE_OPTIONS} && make.exe'

after_build:
  - cd os\windows && dobuild.cmd %PLATFORM%

artifacts:
  - path: os\windows\*.msi
    name: msi
